version: '2'
services:
    aso-app:
        image: aso
        external_links:
            - aso-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aso?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    aso-mysql:
        extends:
            file: mysql.yml
            service: aso-mysql
