version: '2'
services:
    aso-app:
        image: aso
        external_links:
            - aso-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/Aso
        ports:
            - 8080:8080
    aso-postgresql:
        extends:
            file: postgresql.yml
            service: aso-postgresql
